# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13GrgPktIlmSpbu5UVFy-EhsIAW0conHN
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

np.random.seed(42)

rows = 3000

data = pd.DataFrame({
    "CustomerID": range(1, rows + 1),
    "Age": np.random.randint(18, 70, rows),
    "Gender": np.random.choice(["Male", "Female"], rows),
    "SubscriptionType": np.random.choice(
        ["Basic", "Premium", "Enterprise"], rows),
    "MonthlyCharges": np.random.randint(300, 2500, rows),
    "TenureMonths": np.random.randint(1, 60, rows),
    "SupportTickets": np.random.randint(0, 10, rows),
    "PaymentMethod": np.random.choice(
        ["Credit Card", "UPI", "Net Banking"], rows),
    "SatisfactionScore": np.random.randint(1, 11, rows),
    "UsageHoursPerWeek": np.random.randint(1, 40, rows)
})

churn = []

for i in range(rows):

    score = 0

    if data.loc[i, "SatisfactionScore"] <= 4:
        score += 2

    if data.loc[i, "SupportTickets"] >= 5:
        score += 2

    if data.loc[i, "TenureMonths"] <= 12:
        score += 2

    if data.loc[i, "UsageHoursPerWeek"] <= 10:
        score += 2

    if data.loc[i, "SubscriptionType"] == "Basic":
        score += 1

    if score >= 5:
        churn.append("Yes")
    else:
        churn.append("No")

data["Churn"] = churn

data.to_csv(r"C:\Users\Admin\Downloads\customer_churn_dataset.csv", index=False)

print(data.head())

print(data.isnull().sum())

data.drop_duplicates(inplace=True)

encoder = LabelEncoder()

for col in ["Gender",
            "SubscriptionType",
            "PaymentMethod",
            "Churn"]:

    data[col] = encoder.fit_transform(data[col])

plt.figure(figsize=(6,6))

data["Churn"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%")

plt.title("Churn Distribution")

plt.show()

sns.countplot(
    x="SubscriptionType",
    hue="Churn",
    data=data)

plt.show()

plt.figure(figsize=(10,8))

sns.heatmap(
    data.corr(),
    annot=True,
    cmap="coolwarm")

plt.show()

plt.hist(
    data["MonthlyCharges"],
    bins=20)

plt.title("Monthly Charges")

plt.show()

X = data.drop(["CustomerID", "Churn"], axis=1)

y = data["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42)

model = RandomForestClassifier()

model.fit(X_train, y_train)

prediction = model.predict(X_test)

print("Accuracy")

print(accuracy_score(y_test, prediction))

print(classification_report(y_test, prediction))

print(confusion_matrix(y_test, prediction))

try:
    age = int(input("Age: "))
    subscription = input("Subscription (Basic/Premium/Enterprise): ")
    charges = float(input("Monthly Charges: "))
    tenure = int(input("Tenure Months: "))
    tickets = int(input("Support Tickets: "))
    satisfaction = int(input("Satisfaction Score (1-10): "))
    usage = float(input("Usage Hours Per Week: "))

    if not (18 <= age <= 100):
        raise ValueError("Age must be between 18 and 100.")

    if not (1 <= satisfaction <= 10):
        raise ValueError("Satisfaction score must be between 1 and 10.")

    gender = 0
    payment = 0

    subscription_map = {
        "Basic": 0,
        "Enterprise": 1,
        "Premium": 2
    }

    if subscription not in subscription_map:
        raise ValueError("Invalid subscription type.")

    sample = [[
        age,
        gender,
        subscription_map[subscription],
        charges,
        tenure,
        tickets,
        payment,
        satisfaction,
        usage
    ]]

    result = model.predict(sample)

    if result[0] == 1:
        print("\nCustomer Likely to Churn")
    else:
        print("\nCustomer Likely to Stay")

except ValueError as e:
    print("Input Error:", e)

except Exception as e:
    print("Unexpected Error:", e)

